default: &default
  adapter: postgresql
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'flat_cms_development' } %>

production:
  <<: *default
